#define OPENGL_BACKEND 1
#define RENDER_BACKEND OPENGL_BACKEND
#define OPENGL_MAJOR 3
#define OPENGL_MINOR 1

#define PHYSICS_TIME_STEP 0.002f

#define DEFINES_SOUNDS_FOLDER "sounds/"
#define DEFINES_AUDIO_SAMPLE_RATE 44100

#if DEVELOPER_MODE
#define RESOURCE_PATH_EXTENSION "../res/" 
#else 
#define RESOURCE_PATH_EXTENSION "res/"
#define NDEBUG
#endif